# Generated by Django 3.1.1 on 2020-09-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0002_auto_20200923_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True, unique=True)),
                ('error', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('error__isnull', True), ('value__isnull', False)), models.Q(('error__isnull', False), ('value__isnull', True)), _connector='OR'), name='maths_result_value_error_together'),
        ),
    ]
